### ISSUE TITLE
Cant forcestart

### ISSUE THREAD

**Issue by KeparYTbcc** [andrei1058/BedWars1058#194]
plugin list:
```
[09:19:34 INFO]: Plugins (44): WorldEdit, GoldenGG, Essentials, PlaceholderAPI, PlugMan, BedWarsFireballFix, tpLogin, ServersNPC, VoidSpawn, HamsterAPI, Kaboom, SkinsRestorer, GSigns, DeluxeMenus, InteractiveBooks, PermissionsEx, ExploitFixer, GrapplingHook, ViaVersion, Vault, TokenManager, LeakParkour, Visible-Players, ProtocolLib, Citizens, RankCommand, ajLeaderboards, BedWars1058, BedWars1058-PopUpTowers, BedWars1058-GenSplit, TAB, BedWars1058-BedBreakEffect, CustomPayloadFixer, MinigamesAddons, GadgetsMenu, Matrix, BedWars1058-Sponge, BedWars1058-LobbyEffect, BedWars1058-addon, HolographicDisplays, LiteBans, BedWars1058-Compass, HolographicExtension, UltraDeliveryMan
```

logs:

```
[09:14:51 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[09:14:51 WARN]:        at org.leakparkour.l.b.getField(Reflection.java:82)

[09:14:51 WARN]:        at org.leakparkour.l.b.k(Reflection.java:41)

[09:14:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[09:14:51 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[09:14:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)

[09:14:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[09:14:51 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[09:14:51 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[09:14:51 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[09:14:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[09:14:53 WARN]: java.lang.NoSuchFieldException: modifiers

[09:14:53 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[09:14:53 WARN]:        at org.leakparkour.l.b.getField(Reflection.java:82)

[09:14:53 WARN]:        at org.leakparkour.l.b.k(Reflection.java:41)

[09:14:53 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[09:14:53 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[09:14:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)

[09:14:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[09:14:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[09:14:53 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[09:14:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[09:14:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[09:15:12 WARN]: java.lang.NoSuchFieldException: modifiers

[09:15:12 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[09:15:12 WARN]:        at org.leakparkour.l.b.getField(Reflection.java:82)

[09:15:12 WARN]:        at org.leakparkour.l.b.k(Reflection.java:41)

[09:15:12 WARN]:        at org.leakparkour.g.a.a(Hologram.java:367)

[09:15:12 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[09:15:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)

[09:15:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[09:15:12 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[09:15:12 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[09:15:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[09:15:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[09:15:15 WARN]: java.lang.NoSuchFieldException: modifiers

[09:15:15 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[09:15:15 WARN]:        at org.leakparkour.l.b.getField(Reflection.java:82)

[09:15:15 WARN]:        at org.leakparkour.l.b.k(Reflection.java:41)

[09:15:15 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[09:15:15 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[09:15:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)

[09:15:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[09:15:15 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[09:15:15 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[09:15:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[09:15:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[09:15:20 WARN]: java.lang.NoSuchFieldException: modifiers

[09:15:20 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[09:15:20 WARN]:        at org.leakparkour.l.b.getField(Reflection.java:82)

[09:15:20 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[09:15:20 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[09:15:20 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[09:15:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)

[09:15:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[09:15:20 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[09:15:20 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[09:15:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[09:15:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[09:15:21 WARN]: java.lang.NoSuchFieldException: modifiers

[09:15:21 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[09:15:21 WARN]:        at org.leakparkour.l.b.getField(Reflection.java:82)

[09:15:21 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[09:15:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[09:15:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[09:15:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)

[09:15:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[09:15:21 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[09:15:21 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[09:15:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[09:15:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[09:15:29 WARN]: java.lang.NoSuchFieldException: modifiers

[09:15:29 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[09:15:29 WARN]:        at org.leakparkour.l.b.getField(Reflection.java:82)

[09:15:29 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[09:15:29 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[09:15:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[09:15:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)

[09:15:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[09:15:29 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[09:15:29 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[09:15:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[09:15:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MherZaqaryan** [comment]
This is not even an issue from bedwars1058

**Comment by Askarionn** [comment]
This error is from "LeakParkour"

**Comment by KeparYTbcc** [comment]
how ever /bw start debug,
fixed that

- Kepar
________________________________

**Comment by reussy** [comment]
> 
that doesn't fix anything, that command is to start a game in debug mode

the problem you report should be reported to the author of the plugin "**LeakParkour**", please close this error
